# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DevelopInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DevelopInterface(object):
    def setupUi(self, DevelopInterface):
        DevelopInterface.setObjectName("DevelopInterface")
        DevelopInterface.resize(776, 649)
        self.gridLayout = QtWidgets.QGridLayout(DevelopInterface)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.CardWidget = CardWidget(DevelopInterface)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_2.setContentsMargins(35, 35, 35, 35)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ChooseFileIcon = IconWidget(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChooseFileIcon.sizePolicy().hasHeightForWidth())
        self.ChooseFileIcon.setSizePolicy(sizePolicy)
        self.ChooseFileIcon.setMinimumSize(QtCore.QSize(24, 24))
        self.ChooseFileIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.ChooseFileIcon.setObjectName("ChooseFileIcon")
        self.horizontalLayout.addWidget(self.ChooseFileIcon)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.ChooseFileLabel = BodyLabel(self.CardWidget)
        self.ChooseFileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ChooseFileLabel.setObjectName("ChooseFileLabel")
        self.verticalLayout_3.addWidget(self.ChooseFileLabel)
        self.ChooseFileButton = PrimaryPushButton(self.CardWidget)
        self.ChooseFileButton.setMinimumSize(QtCore.QSize(200, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/gallery/images/icons/Menu_black.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChooseFileButton.setIcon(icon)
        self.ChooseFileButton.setProperty("hasIcon", False)
        self.ChooseFileButton.setObjectName("ChooseFileButton")
        self.verticalLayout_3.addWidget(self.ChooseFileButton)
        self.ChooseFileDrop = DropDownPushButton(self.CardWidget)
        self.ChooseFileDrop.setMinimumSize(QtCore.QSize(150, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/gallery/images/icons/Grid_black.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ChooseFileDrop.setIcon(icon1)
        self.ChooseFileDrop.setProperty("hasIcon", True)
        self.ChooseFileDrop.setObjectName("ChooseFileDrop")
        self.verticalLayout_3.addWidget(self.ChooseFileDrop)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.CardWidget, 2, 1, 1, 1)

        self.retranslateUi(DevelopInterface)
        QtCore.QMetaObject.connectSlotsByName(DevelopInterface)

    def retranslateUi(self, DevelopInterface):
        _translate = QtCore.QCoreApplication.translate
        DevelopInterface.setWindowTitle(_translate("DevelopInterface", "Form"))
        self.ChooseFileLabel.setText(_translate("DevelopInterface", "Выберите файл (.tstf)"))
        self.ChooseFileButton.setText(_translate("DevelopInterface", "Обзор"))
        self.ChooseFileDrop.setText(_translate("DevelopInterface", "Из недавних"))
from qfluentwidgets import BodyLabel, CardWidget, DropDownPushButton, IconWidget, PrimaryPushButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DevelopInterface = QtWidgets.QWidget()
    ui = Ui_DevelopInterface()
    ui.setupUi(DevelopInterface)
    DevelopInterface.show()
    sys.exit(app.exec_())
